ports:
  - name: Webserver
    description: voor simulator site
    port: 8080
    onOpen: notify
tasks:
  - name: webserver
    command: npx --yes http-server -c-1 # webserver on port 8080 no cache
  - name: shell
    command: >
